# Generated by Django 2.2 on 2020-04-30 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Description',
        ),
    ]
