# Generated by Django 2.2 on 2020-04-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_delete_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default='something'),
            preserve_default=False,
        ),
    ]
